# Generated by Django 3.2.6 on 2021-09-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_urer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='urer',
            new_name='user',
        ),
    ]
